### ISSUE TITLE
GetTopologyCommonAncestor method error

### ISSUE THREAD

**Issue by lengrongfu** [NVIDIA/go-nvlib#16]
https://github.com/NVIDIA/go-nvlib/blob/f3264c8a6a7a679478f42aff748b3dc81c334ed0/pkg/nvml/device.go#L183-L190
```
other, ok := o.(nvmlDevice)
	if !ok {
		return 0, ERROR_INVALID_ARGUMENT
	}
```

this `ok` is false, i don't now why, anybody can help me.

<img width="600" alt="image" src="https://github.com/NVIDIA/go-gpuallocator/assets/15009201/933ea1cb-01af-4ed6-89d4-ccca6885ae7b">

**Comment by elezar** [comment]
@lengrongfu it may have to do with where you're calling this function from. The `o` argument is an `gpuallocator.nvlibDevice` which is *not* an `nvmlDevice`. I think this highlights a bug in the way we use this code from `go-gpuallocator` and I will have a look at reproducing this locally and addressing it.

**Comment by elezar** [comment]
@lengrongfu I created #17 and https://github.com/NVIDIA/go-gpuallocator/pull/22 to address this issue. I also added a simple example there where I verified the behaviour that you are seeing and that this is addressed by these changes.

**Comment by elezar** [comment]
@lengrongfu could you confirm that this issue is resolved with the linked issues merged?

**Comment by lengrongfu** [comment]
@elezar Thanks for the fix, no problem anymore.
